export const TRAER_TODAS = 'tareas_traer_usuarios'
export const LOADING = 'tareas_loading'
export const ERROR = 'tareas_error'
export const CAMBIO_USUARIO = 'cambio_usuario_id'
export const CAMBIO_TITULO = 'cambio_titulo'
export const GUARDAR = 'guardar'
export const ACTUALIZAR = 'actualizar'
export const LIMPIAR = 'limpiar'
